[vlang]
format = "via [$symbol($version )]($style)"
version_format = "v${raw}"
symbol = "V "
style = "blue bold"
disabled = false
detect_extensions = ["v"]
detect_files = [
    "v.mod",
    "vpkg.json",
    ".vpkg-lock.json",
]
detect_folders = []

[zig]
format = "via [$symbol($version )]($style)"
version_format = "v${raw}"
symbol = "↯ "
style = "bold yellow"
disabled = false
detect_extensions = ["zig"]
detect_files = []
detect_folders = []

[custom]
